import "./globals.css";
import type { Metadata } from "next";
import QueryClientProvider from "@/components/(query)/QueryClientProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <main>
          <QueryClientProvider>{children}</QueryClientProvider>
        </main>
      </body>
    </html>
  );
}
